<?php
/**
 * SapiV1SubAccountUniversalTransferGet200ResponseInner
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Binance Public Spot API
 *
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * SapiV1SubAccountUniversalTransferGet200ResponseInner Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SapiV1SubAccountUniversalTransferGet200ResponseInner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = '_sapi_v1_sub_account_universalTransfer_get_200_response_inner';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'tran_id' => 'int',
        'from_email' => 'string',
        'to_email' => 'string',
        'asset' => 'string',
        'amount' => 'string',
        'from_account_type' => 'string',
        'to_account_type' => 'string',
        'status' => 'string',
        'create_time_stamp' => 'int',
        'client_tran_id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'tran_id' => 'int64',
        'from_email' => null,
        'to_email' => null,
        'asset' => null,
        'amount' => null,
        'from_account_type' => null,
        'to_account_type' => null,
        'status' => null,
        'create_time_stamp' => 'int64',
        'client_tran_id' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'tran_id' => false,
		'from_email' => false,
		'to_email' => false,
		'asset' => false,
		'amount' => false,
		'from_account_type' => false,
		'to_account_type' => false,
		'status' => false,
		'create_time_stamp' => false,
		'client_tran_id' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'tran_id' => 'tranId',
        'from_email' => 'fromEmail',
        'to_email' => 'toEmail',
        'asset' => 'asset',
        'amount' => 'amount',
        'from_account_type' => 'fromAccountType',
        'to_account_type' => 'toAccountType',
        'status' => 'status',
        'create_time_stamp' => 'createTimeStamp',
        'client_tran_id' => 'clientTranId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'tran_id' => 'setTranId',
        'from_email' => 'setFromEmail',
        'to_email' => 'setToEmail',
        'asset' => 'setAsset',
        'amount' => 'setAmount',
        'from_account_type' => 'setFromAccountType',
        'to_account_type' => 'setToAccountType',
        'status' => 'setStatus',
        'create_time_stamp' => 'setCreateTimeStamp',
        'client_tran_id' => 'setClientTranId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'tran_id' => 'getTranId',
        'from_email' => 'getFromEmail',
        'to_email' => 'getToEmail',
        'asset' => 'getAsset',
        'amount' => 'getAmount',
        'from_account_type' => 'getFromAccountType',
        'to_account_type' => 'getToAccountType',
        'status' => 'getStatus',
        'create_time_stamp' => 'getCreateTimeStamp',
        'client_tran_id' => 'getClientTranId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('tran_id', $data ?? [], null);
        $this->setIfExists('from_email', $data ?? [], null);
        $this->setIfExists('to_email', $data ?? [], null);
        $this->setIfExists('asset', $data ?? [], null);
        $this->setIfExists('amount', $data ?? [], null);
        $this->setIfExists('from_account_type', $data ?? [], null);
        $this->setIfExists('to_account_type', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('create_time_stamp', $data ?? [], null);
        $this->setIfExists('client_tran_id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['tran_id'] === null) {
            $invalidProperties[] = "'tran_id' can't be null";
        }
        if ($this->container['from_email'] === null) {
            $invalidProperties[] = "'from_email' can't be null";
        }
        if ($this->container['to_email'] === null) {
            $invalidProperties[] = "'to_email' can't be null";
        }
        if ($this->container['asset'] === null) {
            $invalidProperties[] = "'asset' can't be null";
        }
        if ($this->container['amount'] === null) {
            $invalidProperties[] = "'amount' can't be null";
        }
        if ($this->container['from_account_type'] === null) {
            $invalidProperties[] = "'from_account_type' can't be null";
        }
        if ($this->container['to_account_type'] === null) {
            $invalidProperties[] = "'to_account_type' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['create_time_stamp'] === null) {
            $invalidProperties[] = "'create_time_stamp' can't be null";
        }
        if ($this->container['client_tran_id'] === null) {
            $invalidProperties[] = "'client_tran_id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets tran_id
     *
     * @return int
     */
    public function getTranId()
    {
        return $this->container['tran_id'];
    }

    /**
     * Sets tran_id
     *
     * @param int $tran_id tran_id
     *
     * @return self
     */
    public function setTranId($tran_id)
    {
        if (is_null($tran_id)) {
            throw new \InvalidArgumentException('non-nullable tran_id cannot be null');
        }
        $this->container['tran_id'] = $tran_id;

        return $this;
    }

    /**
     * Gets from_email
     *
     * @return string
     */
    public function getFromEmail()
    {
        return $this->container['from_email'];
    }

    /**
     * Sets from_email
     *
     * @param string $from_email from_email
     *
     * @return self
     */
    public function setFromEmail($from_email)
    {
        if (is_null($from_email)) {
            throw new \InvalidArgumentException('non-nullable from_email cannot be null');
        }
        $this->container['from_email'] = $from_email;

        return $this;
    }

    /**
     * Gets to_email
     *
     * @return string
     */
    public function getToEmail()
    {
        return $this->container['to_email'];
    }

    /**
     * Sets to_email
     *
     * @param string $to_email to_email
     *
     * @return self
     */
    public function setToEmail($to_email)
    {
        if (is_null($to_email)) {
            throw new \InvalidArgumentException('non-nullable to_email cannot be null');
        }
        $this->container['to_email'] = $to_email;

        return $this;
    }

    /**
     * Gets asset
     *
     * @return string
     */
    public function getAsset()
    {
        return $this->container['asset'];
    }

    /**
     * Sets asset
     *
     * @param string $asset asset
     *
     * @return self
     */
    public function setAsset($asset)
    {
        if (is_null($asset)) {
            throw new \InvalidArgumentException('non-nullable asset cannot be null');
        }
        $this->container['asset'] = $asset;

        return $this;
    }

    /**
     * Gets amount
     *
     * @return string
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param string $amount amount
     *
     * @return self
     */
    public function setAmount($amount)
    {
        if (is_null($amount)) {
            throw new \InvalidArgumentException('non-nullable amount cannot be null');
        }
        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets from_account_type
     *
     * @return string
     */
    public function getFromAccountType()
    {
        return $this->container['from_account_type'];
    }

    /**
     * Sets from_account_type
     *
     * @param string $from_account_type from_account_type
     *
     * @return self
     */
    public function setFromAccountType($from_account_type)
    {
        if (is_null($from_account_type)) {
            throw new \InvalidArgumentException('non-nullable from_account_type cannot be null');
        }
        $this->container['from_account_type'] = $from_account_type;

        return $this;
    }

    /**
     * Gets to_account_type
     *
     * @return string
     */
    public function getToAccountType()
    {
        return $this->container['to_account_type'];
    }

    /**
     * Sets to_account_type
     *
     * @param string $to_account_type to_account_type
     *
     * @return self
     */
    public function setToAccountType($to_account_type)
    {
        if (is_null($to_account_type)) {
            throw new \InvalidArgumentException('non-nullable to_account_type cannot be null');
        }
        $this->container['to_account_type'] = $to_account_type;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets create_time_stamp
     *
     * @return int
     */
    public function getCreateTimeStamp()
    {
        return $this->container['create_time_stamp'];
    }

    /**
     * Sets create_time_stamp
     *
     * @param int $create_time_stamp create_time_stamp
     *
     * @return self
     */
    public function setCreateTimeStamp($create_time_stamp)
    {
        if (is_null($create_time_stamp)) {
            throw new \InvalidArgumentException('non-nullable create_time_stamp cannot be null');
        }
        $this->container['create_time_stamp'] = $create_time_stamp;

        return $this;
    }

    /**
     * Gets client_tran_id
     *
     * @return string
     */
    public function getClientTranId()
    {
        return $this->container['client_tran_id'];
    }

    /**
     * Sets client_tran_id
     *
     * @param string $client_tran_id client_tran_id
     *
     * @return self
     */
    public function setClientTranId($client_tran_id)
    {
        if (is_null($client_tran_id)) {
            throw new \InvalidArgumentException('non-nullable client_tran_id cannot be null');
        }
        $this->container['client_tran_id'] = $client_tran_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


