<?php
/**
 * SapiV1MarginDribbletGet200ResponseUserAssetDribbletsInnerUserAssetDribbletDetailsInnerTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Binance Public Spot API
 *
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * SapiV1MarginDribbletGet200ResponseUserAssetDribbletsInnerUserAssetDribbletDetailsInnerTest Class Doc Comment
 *
 * @category    Class
 * @description SapiV1MarginDribbletGet200ResponseUserAssetDribbletsInnerUserAssetDribbletDetailsInner
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SapiV1MarginDribbletGet200ResponseUserAssetDribbletsInnerUserAssetDribbletDetailsInnerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SapiV1MarginDribbletGet200ResponseUserAssetDribbletsInnerUserAssetDribbletDetailsInner"
     */
    public function testSapiV1MarginDribbletGet200ResponseUserAssetDribbletsInnerUserAssetDribbletDetailsInner()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "trans_id"
     */
    public function testPropertyTransId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "service_charge_amount"
     */
    public function testPropertyServiceChargeAmount()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "operate_time"
     */
    public function testPropertyOperateTime()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "transfered_amount"
     */
    public function testPropertyTransferedAmount()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "from_asset"
     */
    public function testPropertyFromAsset()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
