<?php
/**
 * SapiV1SubAccountMarginAccountGet200ResponseMarginTradeCoeffVoTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Binance Public Spot API
 *
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * SapiV1SubAccountMarginAccountGet200ResponseMarginTradeCoeffVoTest Class Doc Comment
 *
 * @category    Class
 * @description SapiV1SubAccountMarginAccountGet200ResponseMarginTradeCoeffVo
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SapiV1SubAccountMarginAccountGet200ResponseMarginTradeCoeffVoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SapiV1SubAccountMarginAccountGet200ResponseMarginTradeCoeffVo"
     */
    public function testSapiV1SubAccountMarginAccountGet200ResponseMarginTradeCoeffVo()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "force_liquidation_bar"
     */
    public function testPropertyForceLiquidationBar()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "margin_call_bar"
     */
    public function testPropertyMarginCallBar()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "normal_bar"
     */
    public function testPropertyNormalBar()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
