<?php
/**
 * FuturesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Binance Public Spot API
 *
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * FuturesApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FuturesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for sapiV1FuturesLoanAdjustCollateralHistoryGet
     *
     * Adjust Cross-Collateral LTV History (USER_DATA).
     *
     */
    public function testSapiV1FuturesLoanAdjustCollateralHistoryGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sapiV1FuturesLoanBorrowHistoryGet
     *
     * Cross-Collateral Borrow History (USER_DATA).
     *
     */
    public function testSapiV1FuturesLoanBorrowHistoryGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sapiV1FuturesLoanInterestHistoryGet
     *
     * Cross-Collateral Interest History (USER_DATA).
     *
     */
    public function testSapiV1FuturesLoanInterestHistoryGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sapiV1FuturesLoanLiquidationHistoryGet
     *
     * Cross-Collateral Liquidation History (USER_DATA).
     *
     */
    public function testSapiV1FuturesLoanLiquidationHistoryGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sapiV1FuturesLoanRepayHistoryGet
     *
     * Cross-Collateral Repayment History (USER_DATA).
     *
     */
    public function testSapiV1FuturesLoanRepayHistoryGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sapiV1FuturesTransferGet
     *
     * Get Future Account Transaction History List (USER_DATA).
     *
     */
    public function testSapiV1FuturesTransferGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sapiV1FuturesTransferPost
     *
     * New Future Account Transfer (USER_DATA).
     *
     */
    public function testSapiV1FuturesTransferPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sapiV2FuturesLoanWalletGet
     *
     * Cross-Collateral Wallet V2 (USER_DATA).
     *
     */
    public function testSapiV2FuturesLoanWalletGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
