<?php
/**
 * SavingsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Binance Public Spot API
 *
 * OpenAPI Specifications for the Binance Public Spot API  API documents:   - [https://github.com/binance/binance-spot-api-docs](https://github.com/binance/binance-spot-api-docs)   - [https://binance-docs.github.io/apidocs/spot/en](https://binance-docs.github.io/apidocs/spot/en)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SavingsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SavingsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for sapiV1LendingCustomizedFixedPurchasePost
     *
     * Purchase Fixed/Activity Project (USER_DATA).
     *
     */
    public function testSapiV1LendingCustomizedFixedPurchasePost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sapiV1LendingDailyProductListGet
     *
     * Get Flexible Product List (USER_DATA).
     *
     */
    public function testSapiV1LendingDailyProductListGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sapiV1LendingDailyPurchasePost
     *
     * Purchase Flexible Product (USER_DATA).
     *
     */
    public function testSapiV1LendingDailyPurchasePost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sapiV1LendingDailyRedeemPost
     *
     * Redeem Flexible Product (USER_DATA).
     *
     */
    public function testSapiV1LendingDailyRedeemPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sapiV1LendingDailyTokenPositionGet
     *
     * Get Flexible Product Position (USER_DATA).
     *
     */
    public function testSapiV1LendingDailyTokenPositionGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sapiV1LendingDailyUserLeftQuotaGet
     *
     * Get Left Daily Purchase Quota of Flexible Product (USER_DATA).
     *
     */
    public function testSapiV1LendingDailyUserLeftQuotaGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sapiV1LendingDailyUserRedemptionQuotaGet
     *
     * Get Left Daily Redemption Quota of Flexible Product (USER_DATA).
     *
     */
    public function testSapiV1LendingDailyUserRedemptionQuotaGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sapiV1LendingPositionChangedPost
     *
     * Change Fixed/Activity Position to Daily Position (USER_DATA).
     *
     */
    public function testSapiV1LendingPositionChangedPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sapiV1LendingProjectListGet
     *
     * Get Fixed/Activity Project List(USER_DATA).
     *
     */
    public function testSapiV1LendingProjectListGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sapiV1LendingProjectPositionListGet
     *
     * Get Fixed/Activity Project Position (USER_DATA).
     *
     */
    public function testSapiV1LendingProjectPositionListGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sapiV1LendingUnionAccountGet
     *
     * Lending Account (USER_DATA).
     *
     */
    public function testSapiV1LendingUnionAccountGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sapiV1LendingUnionInterestHistoryGet
     *
     * Get Interest History (USER_DATA).
     *
     */
    public function testSapiV1LendingUnionInterestHistoryGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sapiV1LendingUnionPurchaseRecordGet
     *
     * Get Purchase Record (USER_DATA).
     *
     */
    public function testSapiV1LendingUnionPurchaseRecordGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sapiV1LendingUnionRedemptionRecordGet
     *
     * Get Redemption Record (USER_DATA).
     *
     */
    public function testSapiV1LendingUnionRedemptionRecordGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
